## TEST API

In [2]:
import requests
import json

url_search = "https://api.tech.ec.europa.eu/search-api/prod/rest/search"
url_facet = "https://api.tech.ec.europa.eu/search-api/prod/rest/facet"

headers = {"Accept": "application/json, text/plain, */*"}

In [140]:
query = {
    "bool": {
        "must": [
            {"terms": {"DATASOURCE": ["SEDIA_NONH2020_PROD"]}},
            {"terms": {"status": ["Ongoing"]}},
            {"terms": {"language": ["en"]}},
        ],
        "must_not": [{"terms": {"programId": ["43108390", "31045243"]}}],
    }
}
sort = {"order": "DESC", "field": "es_SortDate"}
fields = [
    "title",
    "acronym",
    "programId",
    "projectId",
    "callIdentifier",
    "programAbbreviation",
    "programmes",
    "status",
    "objectives",
    "participants",
    "topicAbbreviation",
    "topicDescription",
    "overallBudget",
    "euContributionRate",
    "euContributionAmount",
    "freeKeywords",
]
languages = ["en"]

files = {
    "query": ("blob", json.dumps(query), "application/json"),
    "sort": ("blob", json.dumps(sort), "application/json"),
    # "displayFields": ("blob", json.dumps(fields), "application/json"),
    "languages": ("blob", json.dumps(languages), "application/json"),
}

params = {"apiKey": "SEDIA_NONH2020_PROD", "text": "***", "pageSize": 1, "pageNumber": 1}

In [139]:
res = requests.post(url=url_search, headers=headers, params=params, files=files)
res.json()

{'apiVersion': '2.148.3',
 'terms': '***',
 'responseTime': 35,
 'totalResults': 13216,
 'pageNumber': 1,
 'pageSize': 1,
 'sort': '[es_SortDate:DESC]',
 'queryLanguage': {'language': 'en', 'probability': 0.0},
 'bestBets': [],
 'results': [{'apiVersion': '2.148.3',
   'reference': '43252476101319793',
   'url': 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/projects-details/43252476/101319793/SMP',
   'contentType': 'text/plain',
   'language': 'en',
   'databaseLabel': 'SEDIA_NONH2020_PROD',
   'database': 'SEDIA_NONH2020_PROD',
   'summary': 'Improvement of methods for collecting and estimating data for the Labour Cost Index in order to adapt statistics to EU requirements',
   'weight': 0.0,
   'content': 'Improvement of methods for collecting and estimating data for the Labour Cost Index in order to adapt statistics to EU requirements',
   'accessRestriction': False,
   'checksum': '4847EC3511D0747DA455F435367104EA2589E11CE2CA2078AD3C2983B6C5EF1E',
   'metadata': {'es_SortDate': ['2026-07-07T08:59:05.960+0200'],
    'endDate': ['2028-02-29T00:00:00.000+0100'],
    'projectWebsite': [],
    'language': ['en'],
    'deliverables': ['[]'],
    'objective': ["The project is a response to the implementation of the new LMB framework regulation and its implementing acts, including the act for the quarterly Labour Cost Index (LCI). This index is crucial for the ongoing assessment of labour cost developments and cost pressures in the economy, and thus for macroeconomic analysis and EU policy coordination. Ensuring full coverage of the economy, improving international comparability and the timeliness of LCI data are essential for the reliability of statistics used, among other things, as the principal European economic indicators. The LCI is an important tool for monitoring potential inflationary and deflationary risks arising from changes in labour costs as a factor of production.Thanks to its quarterly frequency, the index allows for ongoing analysis of short-term trends in labour costs, which makes it particularly useful in macroeconomic analyses and labour market surveys.\nThe general objective of the project is to support the national official statistics system in adapting LMB statistics to new EU requirements by updating data sources, developing methodologies and improving statistical production processes. The project involves the use and integration of administrative data, streamlining the production cycle and developing methodological solutions that will improve the quality and scope of information while reducing the burden on respondents.The project directly falls within the scope of the call, responding to its priorities in the area of improving statistical methods, increasing the efficiency of production processes and preparing statistical systems for new reporting obligations. Its results – in particular the methodological, organisational and quality solutions developed – will contribute to the achievement of the call's objectives and may serve as a reference point and source of good practice for other Member States, strengthening the the coherence and quality of the European Statistical System.\n"],
    'ecKeywords': [],
    'typeOfMGAs': ['43250793'],
    'callIdentifier': ['SMP-ESS-2025-LMB-IBA'],
    'freeKeywords': ['labour market',
     'LMB',
     'Labour Cost Index',
     'EU requirements'],
    'destinationGroup': [],
    'DATASOURCE': ['SEDIA_NONH2020_PROD'],
    'subProgramme': [],
    'overallBudget': ['84047.72'],
    'pics': ['968204434'],
    'topicDescription': [],
    'typeOfActions': ['43250778'],
    'es_ContentType': ['text/plain'],
    'programmePeriod': ['2021 - 2027'],
    'programmes': ['Single Market Programme (SMP)'],
    'countries': ['20000986'],
    'esST_URL': ['https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/projects-details/43252476/101319793/SMP'],
    'ecSignatureDate': ['2026-07-03T00:00:00.000+0100'],
    'esDA_QueueDate': ['2026-07-07T08:59:05.973+0200'],
    'mission': [],
    'topicId': ['49195711'],
    'topicExists': ['false'],
    'programAbbreviation': ['SMP'],
    'projectId': ['101319793'],
    'startDate': ['2026-06-01T00:00:00.000+0100'],
    'status': ['Ongoing'],
    'subTypeOfAction': [],
    'typeOfAction': ['SMP European Statistics'],
    'projectObjective': ["The project is a response to the implementation of the new LMB framework regulation and its implementing acts, including the act for the quarterly Labour Cost Index (LCI). This index is crucial for the ongoing assessment of labour cost developments and cost pressures in the economy, and thus for macroeconomic analysis and EU policy coordination. Ensuring full coverage of the economy, improving international comparability and the timeliness of LCI data are essential for the reliability of statistics used, among other things, as the principal European economic indicators. The LCI is an important tool for monitoring potential inflationary and deflationary risks arising from changes in labour costs as a factor of production.Thanks to its quarterly frequency, the index allows for ongoing analysis of short-term trends in labour costs, which makes it particularly useful in macroeconomic analyses and labour market surveys.\nThe general objective of the project is to support the national official statistics system in adapting LMB statistics to new EU requirements by updating data sources, developing methodologies and improving statistical production processes. The project involves the use and integration of administrative data, streamlining the production cycle and developing methodological solutions that will improve the quality and scope of information while reducing the burden on respondents.The project directly falls within the scope of the call, responding to its priorities in the area of improving statistical methods, increasing the efficiency of production processes and preparing statistical systems for new reporting obligations. Its results – in particular the methodological, organisational and quality solutions developed – will contribute to the achievement of the call's objectives and may serve as a reference point and source of good practice for other Member States, strengthening the the coherence and quality of the European Statistical System.\n"],
    'destination': [],
    'title': ['Improvement of methods for collecting and estimating data for the Labour Cost Index in order to adapt statistics to EU requirements'],
    'esST_checksum': ['4847EC3511D0747DA455F435367104EA2589E11CE2CA2078AD3C2983B6C5EF1E'],
    'esST_FileName': ['file.txt'],
    'REFERENCE': ['43252476101319793'],
    'topicAbbreviation': ['SMP-ESS-2025-LMB-IBA-H3-7093'],
    'numberOfContributors': ['1'],
    'publicationsAvailable': ['0'],
    'participants': ['[{"role":"coordinator","pic":968204434,"legalName":"GLOWNY URZAD STATYSTYCZNY","postalAddress":{"id":0,"abbreviation":null,"classId":null,"context":null,"description":null,"postalCode":"00 925","street":"AL. NIEPODLEGLOSCI  208","city":"Warszawa","countryCode":{"id":20000986,"abbreviation":"PL","classId":null,"context":null,"description":"Poland","postalCode":null,"street":null,"city":null,"countryCode":null}},"latitude":"52.2110374","longitude":"21.0559848","activityType":"Other","eucontribution":"75642.84","status":"Active","order":1,"organizationType":null,"type":"PUB","webLink":"www.stat.gov.pl","sme":false}]'],
    'programmeDivision': ['43494260'],
    'crossCuttingPriorities': [],
    'acronym': ['2025-PL-LMB'],
    'esDA_FirstIngestDate': ['2026-07-07T08:59:05.984+0200'],
    'esDA_IngestDate': ['2026-07-07T08:59:05.984+0200'],
    'legalEntityNames': ['GLOWNY URZAD STATYSTYCZNY'],
    'euContributionRate': ['90'],
    'url': ['https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/projects-details/43252476/101319793/SMP'],
    'euContributionAmount': ['75642.84'],
    'programDescription': ['Single Market Programme (SMP)'],
    'nutsCode': ['PL91'],
    'awardedBudget': [],
    'fundedUnder': ['Single Market Programme (SMP)'],
    'implementingBody': ['ESTAT'],
    'missionGroup': [],
    'programId': ['43252476'],
    'specificObjective': [],
    'summaries': ['[]'],
    'publications': ['[]']},
   'enrichedMetadata': {},
   'children': [],
   'highlightedFragments': [],
   'citation': 'Improvement of methods for collecting and estimating data for the Labour Cost Index in order to adapt statistics to EU requirements. Available at: https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/projects-details/43252476/101319793/SMP'}],
 'warnings': []}

In [133]:
metadata = res.json().get("results", [])[0].get("metadata")
participants = json.loads(metadata.get("participants")[0])

In [135]:
participants[0]

{'role': 'coordinator',
 'pic': 999975329,
 'legalName': 'UNIVERSITY OF SOUTHAMPTON',
 'postalAddress': {'id': 0,
  'abbreviation': None,
  'classId': None,
  'context': None,
  'description': None,
  'postalCode': 'SO17 1BJ',
  'street': 'Highfield',
  'city': 'SOUTHAMPTON',
  'countryCode': {'id': 20000893,
   'abbreviation': 'UK',
   'classId': None,
   'context': None,
   'description': 'United Kingdom',
   'postalCode': None,
   'street': None,
   'city': None,
   'countryCode': None}},
 'latitude': '50.9357189',
 'longitude': '-1.399466832413353',
 'activityType': 'HSE',
 'eucontribution': '606345.12',
 'status': 'Active',
 'order': 1,
 'organizationType': None,
 'type': 'HES',
 'webLink': 'http://www.southampton.ac.uk',
 'sme': False}

## TEST HARVEST

In [13]:
import pandas as pd

# run eu_projects.py first
projects_df = pd.read_json("eu_projects.jsonl", lines=True)
projects_df.head()

,id,url,type,startDate,endDate,signatureDate,year,acronym,label,description,participantCount,participants,budgetFinanced,callIdentifier,instrument,action,budgetTotal,keywords
0,101181318,https://ec.europa.eu/info/funding-tenders/oppo...,CEF2027,2024-04-01T00:00:00.000+0100,2026-12-31T00:00:00.000+0100,2024-11-21T00:00:00.000+0100,2024,{'default': '23-IT-DIG-BlueMed East'},{'default': 'BlueMed East'},{'default': 'BlueMedEast project is the third ...,1,"[{'role': 'coordinator', 'funding': '14078655'...",14078655.0,{'id': 'CEF-DIG-2023-GATEWAYS'},CEF Infrastructure Projects,"{'code': '43323741', 'label': {'default': 'CEF...",NaN,NaN
1,101175276,https://ec.europa.eu/info/funding-tenders/oppo...,CEF2027,2024-02-01T00:00:00.000+0100,2025-12-31T00:00:00.000+0100,2024-10-07T00:00:00.000+0100,2024,{'default': '23-DE-TG-RPool BL3 locos 2023'},{'default': 'ETCS Baseline 3 upgrades and retr...,"{'default': '""Railpool 7 GmbH & Co. KG, hencef...",1,"[{'role': 'coordinator', 'funding': '1270000',...",1270000.0,{'id': 'CEF-T-2023-SIMOBGEN'},CEF ERTMS Unit Grants,"{'code': '43249483', 'label': {'default': 'CEF...",NaN,NaN
2,101175502,https://ec.europa.eu/info/funding-tenders/oppo...,CEF2027,2024-02-01T00:00:00.000+0100,2028-12-31T00:00:00.000+0100,2024-10-16T00:00:00.000+0100,2024,{'default': '23-ES-TG-OPS VALENCIAPORT'},{'default': 'Onshore power supply for containe...,{'default': 'The final goal of the OPS VALENCI...,5,"[{'role': 'coordinator', 'funding': '168664', ...",23827891.7,{'id': 'CEF-T-2023-COREGEN'},CEF Infrastructure Projects,"{'code': '43323741', 'label': {'default': 'CEF...",NaN,NaN
3,101122660,https://ec.europa.eu/info/funding-tenders/oppo...,CEF2027,2023-07-01T00:00:00.000+0100,2026-09-30T00:00:00.000+0100,2023-10-18T00:00:00.000+0100,2023,{'default': '22-EU-TG-BBT'},{'default': 'Brenner Base Tunnel – Realization...,{'default': 'The global project Brenner Base T...,3,"[{'role': 'coordinator', 'funding': '700000000...",700000000.0,{'id': 'CEF-T-2022-COREGEN'},CEF Infrastructure Projects,"{'code': '43323741', 'label': {'default': 'CEF...",NaN,NaN
4,101122823,https://ec.europa.eu/info/funding-tenders/oppo...,CEF2027,2023-01-19T00:00:00.000+0100,2027-01-18T00:00:00.000+0100,2023-10-12T00:00:00.000+0100,2023,{'default': '22-FR-TG-LNMP-PH1-STUDIES'},{'default': 'New and non-climate vulnerable ra...,{'default': 'The project is part of the Global...,1,"[{'role': 'coordinator', 'funding': '6342431.5...",6342431.5,{'id': 'CEF-T-2022-COREGEN'},CEF Infrastructure Projects,"{'code': '43323741', 'label': {'default': 'CEF...",NaN,NaN

In [14]:
projects_df["type"].value_counts()

type
CERV           19150
SMP            15066
ERASMUS2027     4977
CREA2027        2752
RFCS2027        2320
ESF              947
EDF              930
COSME            864
CEF2027          628
UCPM2027         619
EUAF             514
ISF              484
REC              382
3HP              324
JUST             248
DIGITAL          185
RFCS             160
AMIF             125
ISFP             110
HERC              72
LIFE2027          71
JUST2027          60
SOCPL             46
UCPM              41
AMIF2027          30
TSI               26
EMFF              21
EU4H              20
AGRIP             20
EMFAF             15
PPPA2027          10
JTM                6
ISFB               5
EURATOM2027        4
CCEI               3
LIFE               3
ERDFTA             3
PERI               3
AGRIP2027          2
EPLUS2020          2
BMVI               2
Name: count, dtype: int64

In [34]:
def flatten(xss):
    return [x for xs in xss for x in xs]

In [89]:
from project.server.main.utils import normalize

participants_df = pd.DataFrame.from_records(flatten(projects_df["participants"].to_list()))
participants_df["label"] = participants_df["label"].apply(lambda x: x.get("default"))
participants_df["label_norm"] = participants_df["label"].apply(lambda x: normalize(x))

In [90]:
participants_df.head()

,role,funding,id,label,address,label_norm
0,coordinator,14078655,101181318-01,TELECOM ITALIA SPARKLE SPA,"{'city': 'ROMA', 'country_code': 'IT', 'countr...",telecomitaliasparklespa
1,coordinator,1270000,101175276-01,RAILPOOL 7 GMBH & CO KG,"{'city': 'GRAFELFING', 'country_code': 'DE', '...",railpool7gmbh&cokg
2,coordinator,168664,101175502-01,FUNDACION DE LA COMUNIDAD VALENCIANA PARA LA I...,"{'city': 'Valencia', 'country_code': 'ES', 'co...",fundaciondelacomunidadvalencianaparalainvestig...
3,participant,22786092.1,101175502-02,AUTORIDAD PORTUARIA DE VALENCIA,"{'city': 'Valencia', 'country_code': 'ES', 'co...",autoridadportuariadevalencia
4,participant,455038.6,101175502-03,APM TERMINALS VALENCIA SA,"{'city': 'VALENCIA', 'country_code': 'ES', 'co...",apmterminalsvalenciasa

In [91]:
unique_df = participants_df.groupby("label_norm", as_index=False).agg(
    **{col: (col, "first") for col in participants_df.columns if col != "label_norm"}, count=("label_norm", "size")
)
unique_df.head()

,label_norm,role,funding,id,label,address,count
0,1000x1000crowdbusinessgmbh,participant,347244.43,101256793-02,1000X1000 CROWDBUSINESS GMBH,"{'city': 'GRAZ', 'country_code': 'AT', 'countr...",2
1,1001valises,participant,40116,101055969-03,1001 VALISES,"{'city': 'Bruxelles / Brussel', 'country_code'...",1
2,20picturestomidnight,participant,17287.28,101255661-02,20 Pictures to Midnight,"{'city': 'Enghien', 'country_code': 'BE', 'cou...",2
3,21kutatokozpontalapitvany,participant,126923.75,101147371-03,21 KUTATOKOZPONT ALAPITVANY,"{'city': 'BUDAPEST', 'country_code': 'HU', 'co...",1
4,28digital,coordinator,2250000,101270442-01,28DIGITAL,"{'city': 'Bruxelles / Brussel', 'country_code'...",6

In [92]:
cache_df = pd.read_json("../../../cache_participant.json", orient="index").reset_index()
cache_df = cache_df.rename(columns={"index": "label_norm", 0: "cache_id"})
cache_df

                                               label_norm    cache_id
0                        *universiteparisestmarnelavallee   199320565
1       2.lbbeumrcnrs5558laboratoiredebiometrieetbiolo...  199411998X
2                                            35labiiivlab   478651284
3                                      3a3aalpesautomatic   319995148
4                                          3dceram3dceram   435266598
...                                                   ...         ...
123542                                             terria   821912359
123543                                     theaiinstitute   838225316
123544                                              vates   752155259
123545                                            verdikt   889631123
123546                                          vortex.io   850904202

[123547 rows x 2 columns]

In [93]:
unique_df = unique_df.merge(cache_df, how="left", on="label_norm")
unique_df

,label_norm,role,funding,id,label,address,count,cache_id
0,1000x1000crowdbusinessgmbh,participant,347244.43,101256793-02,1000X1000 CROWDBUSINESS GMBH,"{'city': 'GRAZ', 'country_code': 'AT', 'countr...",2,NaN
1,1001valises,participant,40116,101055969-03,1001 VALISES,"{'city': 'Bruxelles / Brussel', 'country_code'...",1,NaN
2,20picturestomidnight,participant,17287.28,101255661-02,20 Pictures to Midnight,"{'city': 'Enghien', 'country_code': 'BE', 'cou...",2,NaN
3,21kutatokozpontalapitvany,participant,126923.75,101147371-03,21 KUTATOKOZPONT ALAPITVANY,"{'city': 'BUDAPEST', 'country_code': 'HU', 'co...",1,NaN
4,28digital,coordinator,2250000,101270442-01,28DIGITAL,"{'city': 'Bruxelles / Brussel', 'country_code'...",6,NaN
...,...,...,...,...,...,...,...,...
9087,zyraekryeministrit,coordinator,170000,101316435-01,ZYRA E KRYEMINISTRIT,"{'city': 'Prishtina', 'country_code': 'XK', 'c...",2,NaN
9088,zzuzsecologicskopje,participant,69003.75,101259627-05,ZZUZS Eco Logic Skopje,"{'city': 'SKOPJE', 'country_code': 'MK', 'coun...",2,NaN
9089,základnískolaamaterskáskolaolomoucsvatoplukova...,associatedPartner,0,101104523-18,"Základní skola a Materská skola Olomouc, Svato...","{'city': 'Olomouc', 'country_code': 'CZ', 'cou...",1,NaN
9090,ábrahámhegyközsegönkormányzata,associatedPartner,0,101275786-06,Ábrahámhegy Község Önkormányzata,"{'city': 'Abrahamhegy', 'country_code': 'HU', ...",1,NaN
9091,österreichischebundessportorganisationbso,coordinator,320000,101318797-01,Österreichische Bundes-Sportorganisation (BSO),"{'city': 'Wien', 'country_code': 'AT', 'countr...",1,NaN

In [94]:
unique_df["cache_id"].notna().sum()

np.int64(1333)

In [101]:
unique_df = unique_df.sort_values("count", ascending=False)

In [102]:
found = unique_df["cache_id"].notna().sum()
not_found = unique_df.shape[0] - found
print("found", found)
print("not_found", not_found)

found 1333
not_found 7759

In [103]:
unique_df[~unique_df["cache_id"].notna()][["label", "label_norm", "count"]].to_csv(
    "eu_part_to_identify.csv", encoding="utf-8"
)

In [ ]:
unique_df[~unique_df["cache_id"].notna()][["label", "label_norm", "count"]].iloc[100:150]

NameError: name 'unique_df' is not defined